//! Autogenerated weights for pallet_snarcos
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-28, STEPS: `20`, REPEAT: 50, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("chainspec.json"), DB CACHE: 1024

// Executed Command:
// target/release/aleph-node
// benchmark
// pallet
// --chain=chainspec.json
// --pallet=pallet_snarcos
// --extrinsic=*
// --steps=20
// --repeat=50
// --template=.maintain/pallet-weight-template.hbs
// --execution=wasm
// --wasm-execution=compiled
// --output=pallets/snarcos/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_snarcos.
pub trait WeightInfo {
    fn store_key(key_length: u32) -> Weight;
    fn overwrite_key(key_length: u32) -> Weight;
    fn verify_groth16() -> Weight;
    fn verify_gm17() -> Weight;
    fn verify_marlin() -> Weight;
}

impl<I: BenchmarkInfo> WeightInfo for I {

    fn store_key(key_length: u32) -> Weight {
        <I as BenchmarkInfo>::store_key(key_length)
    }

    fn overwrite_key(key_length: u32) -> Weight {
        <I as BenchmarkInfo>::overwrite_key(key_length)
    }

    fn verify_groth16() -> Weight {
        <I as BenchmarkInfo>::verify_groth16_xor()
            .max(<I as BenchmarkInfo>::verify_groth16_linear_equation())
            .max(<I as BenchmarkInfo>::verify_groth16_merkle_tree_8())
            .max(<I as BenchmarkInfo>::verify_groth16_merkle_tree_64())
            .max(<I as BenchmarkInfo>::verify_groth16_merkle_tree_1024())
    }

    fn verify_gm17() -> Weight {
        <I as BenchmarkInfo>::verify_gm17_xor()
            .max(<I as BenchmarkInfo>::verify_gm17_linear_equation())
            .max(<I as BenchmarkInfo>::verify_gm17_merkle_tree_8())
            .max(<I as BenchmarkInfo>::verify_gm17_merkle_tree_64())
            .max(<I as BenchmarkInfo>::verify_gm17_merkle_tree_1024())
    }

    fn verify_marlin() -> Weight {
        <I as BenchmarkInfo>::verify_marlin_xor()
            .max(<I as BenchmarkInfo>::verify_marlin_linear_equation())
            .max(<I as BenchmarkInfo>::verify_marlin_merkle_tree_8())
            .max(<I as BenchmarkInfo>::verify_marlin_merkle_tree_64())
            .max(<I as BenchmarkInfo>::verify_marlin_merkle_tree_1024())
    }

    // TODO: compile results from benchmarks
}


/// Benchmark results for pallet_snarcos.
trait BenchmarkInfo {
        fn store_key(l: u32, ) -> Weight;
        fn overwrite_key(l: u32, ) -> Weight;
        fn delete_key(l: u32, ) -> Weight;
        fn verify_groth16_xor() -> Weight;
        fn verify_groth16_linear_equation() -> Weight;
        fn verify_groth16_merkle_tree_8() -> Weight;
        fn verify_groth16_merkle_tree_64() -> Weight;
        fn verify_groth16_merkle_tree_1024() -> Weight;
        fn verify_gm17_xor() -> Weight;
        fn verify_gm17_linear_equation() -> Weight;
        fn verify_gm17_merkle_tree_8() -> Weight;
        fn verify_gm17_merkle_tree_64() -> Weight;
        fn verify_gm17_merkle_tree_1024() -> Weight;
        fn verify_marlin_xor() -> Weight;
        fn verify_marlin_linear_equation() -> Weight;
        fn verify_marlin_merkle_tree_8() -> Weight;
        fn verify_marlin_merkle_tree_64() -> Weight;
        fn verify_marlin_merkle_tree_1024() -> Weight;
}

/// Weights for pallet_snarcos using the Substrate node and recommended hardware.
pub struct AlephWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> BenchmarkInfo for AlephWeight<T> {
        // Storage: Snarcos VerificationKeys (r:1 w:1)
        fn store_key(l: u32, ) -> Weight {
                (18_321_000 as Weight)
                        // Standard Error: 0
                        .saturating_add((1_000 as Weight).saturating_mul(l as Weight))
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
                        .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:1)
        fn overwrite_key(l: u32, ) -> Weight {
                (8_093_000 as Weight)
                        // Standard Error: 0
                        .saturating_add((1_000 as Weight).saturating_mul(l as Weight))
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
                        .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:0 w:1)
        fn delete_key(_l: u32, ) -> Weight {
                (5_524_000 as Weight)
                        .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_xor() -> Weight {
                (51_752_194_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_linear_equation() -> Weight {
                (40_849_316_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_merkle_tree_8() -> Weight {
                (54_190_927_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_merkle_tree_64() -> Weight {
                (54_175_076_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_merkle_tree_1024() -> Weight {
                (54_562_433_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_xor() -> Weight {
                (57_624_143_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_linear_equation() -> Weight {
                (46_849_191_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_merkle_tree_8() -> Weight {
                (60_235_329_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_merkle_tree_64() -> Weight {
                (60_191_040_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_merkle_tree_1024() -> Weight {
                (60_299_781_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_xor() -> Weight {
                (90_281_258_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_linear_equation() -> Weight {
                (91_693_061_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_merkle_tree_8() -> Weight {
                (88_985_891_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_merkle_tree_64() -> Weight {
                (89_163_774_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_merkle_tree_1024() -> Weight {
                (88_869_816_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
        }
}

// For backwards compatibility and tests
impl BenchmarkInfo for () {
        // Storage: Snarcos VerificationKeys (r:1 w:1)
        fn store_key(l: u32, ) -> Weight {
                (18_321_000 as Weight)
                        // Standard Error: 0
                        .saturating_add((1_000 as Weight).saturating_mul(l as Weight))
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
                        .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:1)
        fn overwrite_key(l: u32, ) -> Weight {
                (8_093_000 as Weight)
                        // Standard Error: 0
                        .saturating_add((1_000 as Weight).saturating_mul(l as Weight))
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
                        .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:0 w:1)
        fn delete_key(_l: u32, ) -> Weight {
                (5_524_000 as Weight)
                        .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_xor() -> Weight {
                (51_752_194_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_linear_equation() -> Weight {
                (40_849_316_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_merkle_tree_8() -> Weight {
                (54_190_927_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_merkle_tree_64() -> Weight {
                (54_175_076_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_groth16_merkle_tree_1024() -> Weight {
                (54_562_433_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_xor() -> Weight {
                (57_624_143_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_linear_equation() -> Weight {
                (46_849_191_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_merkle_tree_8() -> Weight {
                (60_235_329_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_merkle_tree_64() -> Weight {
                (60_191_040_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_gm17_merkle_tree_1024() -> Weight {
                (60_299_781_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_xor() -> Weight {
                (90_281_258_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_linear_equation() -> Weight {
                (91_693_061_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_merkle_tree_8() -> Weight {
                (88_985_891_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_merkle_tree_64() -> Weight {
                (89_163_774_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
        // Storage: Snarcos VerificationKeys (r:1 w:0)
        fn verify_marlin_merkle_tree_1024() -> Weight {
                (88_869_816_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
        }
}
