name: 'Run e2e test'
description: 'Run single e2e test.'

inputs:
  test-case:
    description: 'Name of test to run.'
    required: true
  follow-up-finalization-check:
    description: 'Whether to run a follow up finalizaton check.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Download artifact with docker image
      uses: actions/download-artifact@v2
      with:
        name: aleph-test-docker

    - name: Load node docker image
      shell: bash
      run: docker load -i aleph-node.tar

    - name: Run consensus party
      shell: bash
      run: ./.github/scripts/run_consensus.sh

    - name: Display bootnode logs
      shell: bash
      run: docker logs damian --follow &

    - name: Download artifact with the test suite image
      uses: actions/download-artifact@v2
      with:
        name: aleph-e2e-client

    - name: Load test suite docker image
      shell: bash
      run: docker load -i aleph-e2e-client.tar

    - name: Run single e2e test
      shell: bash
      run: ./.github/scripts/run_e2e_test.sh -t ${{ inputs.test-case }}

    - name: Run finalization e2e test
      if: inputs.follow-up-finalization-check == 'true'
      shell: bash
      run: ./.github/scripts/run_e2e_test.sh -t finalization

    - name: Print debug if failed
      if: ${{ failure() }}
      shell: bash
      run: |
        cd bin/cliain
        cargo run -- --seed //Alice debug-storage
