FROM syntheticnet:latest as synthnet

FROM aleph-node:latest

# Linux networking tools and node.js
RUN apt update && \
    apt install nodejs curl iproute2 iputils-ping net-tools netwox tcpdump gdb gdbserver stress -y

COPY --from=synthnet /opt/lib/ /opt/lib/
WORKDIR /opt/lib
ENTRYPOINT []
ENV ENTRY="/node/docker_entrypoint.sh"
CMD ["/opt/lib/setup.sh"]

