FROM ubuntu:jammy-20220531

RUN apt update && \
        apt install curl -y && \
        apt clean && \
        rm -rf /var/lib/apt/lists/*

EXPOSE 30333 9933 9944

WORKDIR node

COPY target/release/aleph-node /usr/local/bin
RUN chmod +x /usr/local/bin/aleph-node

ENTRYPOINT ["/usr/local/bin/aleph-node"]
