---
name: Build and push Docker Hub image
description:
  Builds and pushes (optionally) docker image to Docker Hub, which does not have bash script as
  entrypoint, just aleph-node.

inputs:
  source-image:
    description: Source aleph-node image
    required: true
  target-image:
    description: Image to build
    required: true
  additional-image:
    description: Additional image to tag
    required: false
  dockerhub-username:
    description: Docker Hub username
    required: true
  dockerhub-password:
    description: Docker Hub password
    required: true

runs:
  using: composite
  steps:
    - name: Build Docker Hub image
      shell: bash
      run: |
        echo "FROM ${{ inputs.source-image }}" > Dockerfile.dockerhub
        echo 'ENTRYPOINT ["/usr/local/bin/aleph-node"]' >> Dockerfile.dockerhub
        docker build -t "${{ inputs.target-image }}" -f Dockerfile.dockerhub .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Push image to Docker Hub
      shell: bash
      run: |
        docker push ${{ inputs.target-image }}
        if [[ -n "${{ inputs.additional-image }}" ]]; then
          docker tag ${{ inputs.source-image }} ${{ inputs.additional-image }}
          docker push ${{ inputs.additional-image }}
        fi
