---
#  This workflow builds production version of aleph-node and aleph-runtime, ie with some
#  features enabled. Those binaries MUST be used in the production.
name: Build production node and runtime
on:
  workflow_call:

jobs:
  main:
    name: Build production node and runtime
    runs-on: self-hosted
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SECRETS_AWS_MAINNET_ACCESS_KEY_ID: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
      SECRETS_AWS_MAINNET_SECRET_ACCESS_KEY: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
      SECRETS_AWS_DEVNET_ACCESS_KEY_ID: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
      SECRETS_AWS_DEVNET_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout aleph-node source code
        uses: actions/checkout@v3

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: ./.github/actions/get-ref-properties

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Build production binary and runtime
        run: cargo build --profile production -p aleph-node

      - name: Upload release binary to GH artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aleph-release-node
          path: target/production/aleph-node
          if-no-files-found: error
          retention-days: 7

      - name: Upload release runtime to GH artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aleph-release-runtime
          path: target/production/wbuild/aleph-runtime/aleph_runtime.compact.wasm
          if-no-files-found: error
          retention-days: 7

      - name: Configure AWS credentials for S3 Mainnet AWS
        if: >
          env.SECRETS_AWS_MAINNET_ACCESS_KEY_ID != '' &&
          env.SECRETS_AWS_MAINNET_SECRET_ACCESS_KEY != ''
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_ACCESS_KEY_ID: ""
          AWS_SECRET_ACCESS_KEY: ""
          AWS_SESSION_TOKEN: ""
          AWS_DEFAULT_REGION: ""
          AWS_REGION: us-east-1
        with:
          aws-access-key-id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy production binary to S3 Mainnet AWS bucket
        if: >
          env.SECRETS_AWS_MAINNET_ACCESS_KEY_ID != '' &&
          env.SECRETS_AWS_MAINNET_SECRET_ACCESS_KEY != ''
        shell: bash
        env:
          BINARY_DIR: target/production
          BINARY_FILE: aleph-node
          # yamllint disable-line rule:line-length
          S3BUCKET_URL: s3://${{ secrets.CI_MAINNET_S3BUCKET_NAME }}/builds/aleph-node/commits/${{ steps.get-ref-properties.outputs.sha }}/aleph-node
          S3BUCKET_FILE: aleph-node-${{ steps.get-ref-properties.outputs.sha }}.tar.gz
        run: |
          tar -cvzf ${{ env.S3BUCKET_FILE }} -C ${{ env.BINARY_DIR }} ${{ env.BINARY_FILE }}
          aws s3 cp ${{ env.S3BUCKET_FILE }} ${{ env.S3BUCKET_URL }}/${{ env.S3BUCKET_FILE }}

      - name: Copy production runtime to S3 Mainnet AWS bucket
        if: >
          env.SECRETS_AWS_MAINNET_ACCESS_KEY_ID != '' &&
          env.SECRETS_AWS_MAINNET_SECRET_ACCESS_KEY != ''
        shell: bash
        env:
          BINARY_DIR: target/production/wbuild/aleph-runtime
          BINARY_FILE: aleph_runtime.compact.wasm
          # yamllint disable-line rule:line-length
          S3BUCKET_URL: s3://${{ secrets.CI_MAINNET_S3BUCKET_NAME }}/builds/aleph-node/commits/${{ steps.get-ref-properties.outputs.sha }}/aleph-runtime
          S3BUCKET_FILE: aleph-runtime-${{ steps.get-ref-properties.outputs.sha }}.tar.gz
        run: |
          tar -cvzf ${{ env.S3BUCKET_FILE }} -C ${{ env.BINARY_DIR }} ${{ env.BINARY_FILE }}
          aws s3 cp ${{ env.S3BUCKET_FILE }} ${{ env.S3BUCKET_URL }}/${{ env.S3BUCKET_FILE }}
