---
# this workflow builds rustdoc for aleph-node crates
name: build-docs

on:
  pull_request:
    paths:
      - 'aleph-client/**'
      - .github/workflows/build-docs.yaml

jobs:
  build-aleph-client-docs:
    name: Build docs
    runs-on: self-hosted
    steps:
      - name: GIT | Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: rustdoc | Build aleph-client docs
        run: |
          cd aleph-client && cargo doc --no-deps
